dataset_path: "./in_frames/normal/data/"
config_path: "./config/configs.yml"
input_ext: ".raw"
rev_yuv: False
# DUT options = ['crop', 'dead_pixel_correction', 'black_level_correction',
#                'oecf', 'digital_gain','bayer_noise_reduction',
#                'white_balance', 'demosaic', 'color_correction_matrix',
#                'gamma_correction', 'color_space_conversion', 'ldci',
#                '2d_noise_reduction', 'rgb_conversion', 'invalid_region_crop',
#                'scale', 'yuv_conversion_format']
dut: ["dead_pixel_correction"]
crop:
  is_enable: false
dead_pixel_correction:
  is_enable: true
black_level_correction:
  is_enable: true
oecf:
  is_enable: false
digital_gain:
  is_save: false
bayer_noise_reduction:
  is_enable: false
auto_white_balance:
  is_enable: true
white_balance:
  is_enable: true
demosaic:
  is_save: false
color_correction_matrix:
  is_enable: true
gamma_correction:
  is_enable: true
auto_exposure:
  is_enable: true
color_space_conversion:
  is_save: false
ldci:
  is_enable: false
2d_noise_reduction:
  is_enable: false
rgb_conversion:
  is_enable: true
invalid_region_crop:
  is_enable: False
scale:
  is_enable: false
yuv_conversion_format:
  is_enable: false
