dataset_path: "./in_frames/normal/data/"
config_path: "./config/configs.yml"
rev_yuv: True
video_mode: true
# DUT options = ['crop', 'dead_pixel_correction', 'black_level_correction',
#                'oecf', 'digital_gain','bayer_noise_reduction',
#                'white_balance', 'demosaic', 'color_correction_matrix',
#                'gamma_correction', 'color_space_conversion',
#                '2d_noise_reduction', 'rgb_conversion', 'invalid_region_crop',
#                'scale', 'yuv_conversion_format']
dut: [dead_pixel_correction,digital_gain,white_balance,demosaic,color_space_conversion, rgb_conversion, invalid_region_crop]
crop:
  is_enable: false
dead_pixel_correction:
  is_enable: false
black_level_correction:
  is_enable: false
oecf:
  is_enable: false
digital_gain:
  is_save: false
bayer_noise_reduction:
  is_enable: false
auto_white_balance:
  is_enable: false
white_balance:
  is_enable: false
demosaic:
  is_save: false
color_correction_matrix:
  is_enable: false
gamma_correction:
  is_enable: false
auto_exposure:
  is_enable: false
color_space_conversion:
  is_save: false
2d_noise_reduction:
  is_enable: false
rgb_conversion:
  is_enable: false
invalid_region_crop:
  is_enable: false
scale:
  is_enable: false
yuv_conversion_format:
  is_enable: false
